name: Restart dev containers

on:
  workflow_dispatch:

jobs:
  restart-dev:
    name: restart dev containers
    runs-on: ubuntu-latest
    environment: dev
    strategy:
      matrix:
        container: ["ckan", "ckanCron"]
    steps:
      - name: configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.0.1
        with:
          role-to-assume: ${{ secrets.AWS_DEV_DEPLOY_ROLE }}
          role-session-name: github-actions
          aws-region: eu-north-1

      - name: Restart containers
        run: |
          aws ecs update-service --cluster ${{ env.cluster }} --service ${{ matrix.container }} --force-new-deployment
        env:
          cluster: ${{ secrets.cluster }}
