name: Run security scans

on:
  workflow_dispatch:
  push:

jobs:
  sast-scanner:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_SCAN_ROLE }}
          role-session-name: github-actions
          aws-region: eu-west-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registries: ${{ secrets.TOOLS_REGISTRY }}


      - name: Pull sast scanner
        run: |
          docker pull $REGISTRY/$REPOSITORY/sast-scanner-meta:latest
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: ${{ secrets.TOOLS_REPOSITORY }}

      - name: Run sast scanner
        run: |
          docker run --rm -v ".:/src" -e LEVEL=HIGH -e TARGET=app -e FORMAT=html -e OUTDIR='/src/scan-results' $REGISTRY/$REPOSITORY/sast-scanner-meta:latest
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: ${{ secrets.TOOLS_REPOSITORY }}


      - name: upload results
        uses: actions/upload-artifact@v4
        with:
          name: sast-scanner-results
          path: scan-results/*
