name: Run security scans

on:
  workflow_dispatch:
  push:

jobs:
  sast-scanner:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_SCAN_ROLE }}
          role-session-name: github-actions
          aws-region: eu-west-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registries: ${{ secrets.TOOLS_REGISTRY }}

      - name: Run sast scanner
        run: |
          docker run --rm -v ".:/src" -e LEVEL=HIGH -e TARGET=app -e FORMAT=sarif  $REGISTRY/$REPOSITORY/sast-scanner-meta:v1.0.0
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: ${{ secrets.TOOLS_REPOSITORY }}


      - name: upload results to advanced security
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep-app-report.sarif
